#!/usr/bin/env php
<?php

declare(strict_types=1);

use Common\Infra\Config\Config;
use Yiisoft\Yii\Runner\Console\ConsoleApplicationRunner;

require_once __DIR__ . '/vendor/autoload.php';

if (empty($_ENV['ENVIRONMENT']) && class_exists(\Dotenv\Dotenv::class)) {
    \Dotenv\Dotenv::createImmutable(__DIR__)->safeLoad();
}

$config = new Config();
$environment = $config->environment();
$debug = $config->isDev();

// Run console application runner
$runner = new ConsoleApplicationRunner(
    rootPath: __DIR__,
    debug: $debug,
    checkEvents: $debug,
    environment: $environment->value,
    configDirectory: 'common/config',
);
$runner->run();
