server {
    listen 8080;
    server_name admin-api.app.test;

    client_max_body_size 520m;

    root /app/admin-api/web;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /openapi.yml {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;

        fastcgi_param HTTP_COOKIE $http_cookie;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;

        fastcgi_param HTTP_COOKIE $http_cookie;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
    }
}
